
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Mongo Library</title>
<link href="style/main.css" rel="stylesheet" type="text/css"><!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<link href="style/form.css" rel="stylesheet" type="text/css">
</head>

<body>

<div class="container">
  <header>
    <a href="index.php"><img src="" alt="Insert Logo Here" width="180" height="90" id="Insert_logo" style="background-color: #C6D580; display:block;" /></a>
  </header>
  <div class="sidebar1">
    <ul class="nav">
      <li><a href="cadastro.php">Cadastro</a></li>
      <li><a href="consulta.php">Consulta</a></li>
      <!--<li><a href="#">Link three</a></li>
      <li><a href="#">Link four</a></li>-->
    </ul>
    <aside>
      <p> Nada </p>
    </aside>
    </div><!-- end .sidebar1 -->